### ISSUE TITLE
Not working with Gnome 3.36.4

### ISSUE THREAD

**Issue by Meijuh** [mheine/gnome-shell-spotify-label#6]
I just updated my Fedora 32, now Gnome version 3.36.4 is installed. Looking glass provides the following error for this extension.

    TypeError: this.actor.reparent is not a function

I Like the extension a lot, I hope it's fixable.

**Comment by raujonas** [comment]
Have you installed the extension from extensions.gnome.org? You could try the current master branch, I think we fixed this issue already but we had a problem with the review of the new version to get it into the official repository. 

Will have a look into this now, so hopefully the new version is online soon.
