### PR TITLE
Disconnect all signals

### LINKED ISSUE #6: Not working with Gnome 3.36.4
I just updated my Fedora 32, now Gnome version 3.36.4 is installed. Looking glass provides the following error for this extension.

    TypeError: this.actor.reparent is not a function

I Like the extension a lot, I hope it's fixable.

### PR DESCRIPTION
**Pull request by raujonas**
The various connections are now stored and disconnected afterwards. I hope this is the right way, but since every time I re-enable the extension each of these connections has a different id it seems good to me.

Edit: Should also fix #6 after successful review.

### CODE REVIEW

**Comment by raujonas** [comment]
Hi @mheine, I just wanted to follow up shortly on my PR. What do you think about it? I really think there would be some happy people out there if we could make it work again.

**Comment by mheine** [comment]
Apologies for the delay, code looks good to me!
